### ISSUE TITLE
Problème de certificat https

### ISSUE THREAD

**Issue by GurYN** [tcs-france/workshop-efrei2023#1]
Voir discussion plus bas

**Comment by GurYN** [comment]
<img width="1135" alt="image" src="https://github.com/tcs-france/workshop-efrei2023/assets/577308/ae786273-d56c-4f7d-bc29-a29c0f2403e7">

**Comment by RomainMarques** [comment]
Bonjour,
Je suis bloqué à l'étape d/e du lab 2. En effet, j'arrive bien à accéder au site, cependant lorsque je renseigne mes informations et me connecte, le site reste bloqué sur la page de confirmation d'inscription, mais ne passe pas à la page des questions. En regardant dans la console, le fetch n'arrive pas à s'exécuter. Auriez-vous une idée d'où le problème pourrait venir?
Voici un screen du problème : 
<img width="1728" alt="Capture d’écran 2023-05-10 à 21 04 24" src="https://github.com/tcs-france/workshop-efrei2023/assets/77971683/6ab7345d-b325-4e07-8150-7f7d78362bb3">

**Comment by GurYN** [comment]
Que dit la console de l'API exam-api ? Des exceptions sont levées ?

**Comment by PlugNPush** [comment]
J'ai eu le même problème, la solution est d'ouvrir le lien https...:7211 dans un nouvel onglet et de faire confiance au certificat SSL non signé. Une fois qu'il est de confiance, le front charge les questions

**Comment by GurYN** [comment]
Il est bizarre que lorsque vous ayez lancé pour la première fois l'API, vous n'ayez pas eu de notification pour la création du certificat auto-signé.

Une commande existe pour la création de ce certificat : `dotnet dev-certs https --trust`

Le certificat sera donc généré et la machine fera confiance à ce certificat.
