### ISSUE TITLE
Lab3 - Azure: Comment paramétrer le mot de passe "ACR" dans le Deployment Center?

### ISSUE THREAD

**Issue by PlugNPush** [tcs-france/workshop-efrei2023#3]
Erreur de départ : 

2023-05-10T22:15:12.025Z ERROR - DockerApiException: Docker API responded with status code=InternalServerError, response={"message":"Get \"https://efreitcsworkshopregistry.azurecr.io/v2/front/manifests/latest\": unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information."}
2023-05-10T22:15:12.027Z WARN  - Image pull failed. Defaulting to local copy if present.
2023-05-10T22:15:12.030Z ERROR - Image pull failed: Verify docker image configuration and credentials (if using private repository)
2023-05-10T22:15:17.596Z INFO  - Stopping site efrei-tcs-workshop-front because it failed during startup.ont_0_f4236308_msiProxy -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME=efrei-tcs-workshop-front.azurewebsites.net -e WEBSITE_INSTANCE_ID=2be45dc8513a5aac1cf08dd2678a9eef1fadfe1da35589acd5d4c13ba7087e1d -e WEBSITE_USE_DIAGNOSTIC_SERVER=False mcr.microsoft.com/appsvc/msitokenservice:stage1

J'ai activé le mot de passe administrateur dans le Registry, puis dans le Deployment Center du front (même problème pour l'autre déploiement via Docker) j'ai sélectionné Credentials, ce qui m'a permis de choisir l'image souhaitée ainsi que son tag.

En revanche, je ne trouve pas où insérer le mot de passe admin pour que Docker puisse pull l'image par lui-même, sans produire l'erreur ci-dessus.

**Comment by GurYN** [comment]
Est ce que la CLI Docker est connectée au registry Azure ?

Les étapes pour pousser une image docker sur le registry Azure : 
- Connecter la CLI Docker sur le registry (par la commande Docker ou en utilisant la CLI Azure)
- Nommer l'image pour qu'elle soit identifiable sur le registry : [NAMESPACE].azurecr.io/[NOM_IMAGE]:[version]

**Comment by PlugNPush** [comment]
Côté local tout est en ordre (l'image est en ligne). 

Côté Azure, c'est pas bien clair comment connecter la CLI Docker sur le registry...

<img width="1639" alt="image" src="https://github.com/tcs-france/workshop-efrei2023/assets/31410359/42c4f6ee-b4a2-4123-b21a-130403d78a2c">

**Comment by GurYN** [comment]
C'est bien configuré sur Azure, l'authentification se fait directement car l'option Admin Account est activée.

Pour aller un peu plus loin, l'activation du déploiement continu permettra à la Web App de charger une nouvelle instance de la dernière version de l'image lorsqu'une nouvelle sera publiée.

Pour vérifier que le container est instansié, on peut aller voir dans les logs au niveau du Log Stream.

**Comment by PlugNPush** [comment]
Le message d'erreur dans mon tout premier message provient du Log Stream. Le container n'est donc pas instansié...

**Comment by GurYN** [comment]
Ça doit être un problème de cache de synchro. Essaie de redémarrer la Web App.

**Comment by PlugNPush** [comment]
J'ai entièrement recréé les services ... Plus de messages d'erreurs, les logs sont vides, mais l'application ne charge pas pour autant. Les deux déploiement Docker sur Azure produisent le même résultat dans le navigateur : 
<img width="713" alt="image" src="https://github.com/tcs-france/workshop-efrei2023/assets/31410359/552c42fd-0c9c-46e7-96c4-ede9ba8a8896">

Le lien de diagnostic ne donne aucune information. J'ai bien mis le port à 3000 dans WEBSITES_PORT.

**Comment by PlugNPush** [comment]
Je retire, miraculeusement ça s'est mis a marcher alors que je n'ai rien touché

**Comment by PlugNPush** [comment]
<img width="1639" alt="image" src="https://github.com/tcs-france/workshop-efrei2023/assets/31410359/61605f97-beb8-4c2b-8712-4eacacb67c80">

Hormis le fait que cette fois il ne se passe rien en essayant de s'inscrire, est-ce dû à des réglages pour la mise en production ? (/undefined/signup 404)

**Comment by GurYN** [comment]
Le fait que cela se mette à marcher n'a rien de miraculeux, c'est juste qu'il y a un délai sur la création de l'instance de l'image.

Pour le problème du front, oui il y a un soucis de configuration. Est-ce que les variables d'environnement ont bien toutes été saisies ? 
<img width="666" alt="image" src="https://github.com/tcs-france/workshop-efrei2023/assets/577308/31cc93e1-58aa-4a55-a7cc-1a9d34a6e5a3">

**Comment by PlugNPush** [comment]
Le délai en question était de 45 minutes environ 😅

Les variables d'environnements sont bien définies et enregistrées. Une fois avec l'API Exam et une fois avec le lien vu en cours. Dans le doute, j'ai ajouté la quatrième variable d'environnement pour l'API Auth, mais cela n'a rien changé.

**Comment by GurYN** [comment]
Ok je viens de comprendre, les noms des variables sur la documentation n'étaient pas bonne, c'est corrigé : 

<img width="690" alt="image" src="https://github.com/tcs-france/workshop-efrei2023/assets/577308/dc88b82e-043e-4dd6-bea7-de9f32092b52">

**Comment by GurYN** [comment]
Une fois modifié, tu devrais normalement en avoir fini avec le déploiement :)

**Comment by PlugNPush** [comment]
![image](https://github.com/tcs-france/workshop-efrei2023/assets/31410359/0dc745e2-79c0-43c3-afd2-9620cac9008c)

Voici a quoi ressemblait déjà mon déploiement avant la modification

**Comment by GurYN** [comment]
La REACT_APP_CENTER_API_URL ne sert à rien, tu peux la supprimer. 

Et restart ta Web App pour que les variables soient injectées dans l'instance du container car l'erreur de la console confirme que la variable de l'url de l'API auth-api n'est pas injectée.

**Comment by PlugNPush** [comment]
Une nouvelle fois sans rien toucher ça a accepté de fonctionner 

En revanche les questions n'apparaissent pas et font planter le front 
![image](https://github.com/tcs-france/workshop-efrei2023/assets/31410359/8ee219bc-622f-4608-bcbe-d5ef09517844)
![image](https://github.com/tcs-france/workshop-efrei2023/assets/31410359/d4a78f2f-9534-4e2c-84bc-ec99552ab5c1)

**Comment by GurYN** [comment]
C'est parce que tu as déjà répondu à ce questionnaire avec ce compte. Il aurait fallu en créer un avec un email différent.

J'ai reset la base côté admin donc supprime de ton côté les variables de ton cache Redis et recommence.

@leabuende : Il faudra gérer cette erreur possible au niveau du front.

**Comment by PlugNPush** [comment]
J'ai à la fois clear les deux variables Redis, et testé avec 2-3 mails aléatoires, mais le problème est toujours là

**Comment by GurYN** [comment]
J'ai pourtant bien la mire de connexion lorsque je lance l'url de ton environnement : 

<img width="1259" alt="image" src="https://github.com/tcs-france/workshop-efrei2023/assets/577308/dcca999b-418d-41b3-abfd-ce35e9b0c7b3">

**Comment by PlugNPush** [comment]
Le formulaire de connexion fonctionne oui, c'est après que ça plante 

Pour CenterApiUrl j'ai gardé l'URL donnée sur le PowerPoint d'hier

**Comment by GurYN** [comment]
Je n'ai pas de compte créé sur la partie admin. Tu peux retester la connexion ?

**Comment by PlugNPush** [comment]
J'ai réessayé, est-ce que ça a fonctionné ?

**Comment by GurYN** [comment]
Oui

<img width="969" alt="image" src="https://github.com/tcs-france/workshop-efrei2023/assets/577308/2f4bb04e-7c3f-4f51-8c2d-2d50d0eb75ac">

**Comment by PlugNPush** [comment]
Ah super, ça a même envoyé mes tentatives de ce matin (la dernière est la premièreière sur la capture d'écran)

**Comment by PlugNPush** [comment]
Est-ce possible de couper les serveurs mais conserver leur configuration sans frais ?

**Comment by GurYN** [comment]
Oui, comme expliqué hier, on ne paye qu'à l'utilisation. Il est donc possible de stopper les services et de ne payer quasi aucun frais (juste le stockage mais qui est insignifiant sur cette architecture).

**Comment by PlugNPush** [comment]
Je peux donc tout éteindre maintenant que j'ai pu le déployer ou il y a encore quelque chose à faire avec ?

**Comment by GurYN** [comment]
Comme indiqué durant le workshop, il y aura les vrais questions sur le système lundi et vous pourrez passer le questionnaire "officiel". Mais jusqu'à lundi oui tu peux éteindre les services.

**Comment by PlugNPush** [comment]
Bien noté, merci. Apparemment on ne peut pas éteindre Redis ni le Registry. On peut que manuellement éteindre les Web Apps et Azure Function, les autres continuent de prélever jusqu'à leur destruction

**Comment by GurYN** [comment]
Oui mais : 

- Azure Cache : 18€/mois
- Service Bus : 0.46€/million d'operation

Donc la facturation pour ces 2 services sur la semaine sera de moins de 5€. Pas d'inquiétude donc, les 100$ de l'offre d'essai seront loin d'être dépassé.
